export const REQUEST_EVENTS_PENDING = "REQUEST_EVENTS_PENDING";
export const REQUEST_EVENTS_SUCCESS = "REQUEST_EVENTS_SUCCESS ";
export const REQUEST_EVENTS_FAILED = "REQUEST_EVENTS_FAILED";

export const REQUEST_EVENT_CREATE_PENDING = "REQUEST_EVENT_CREATE_PENDING";
export const REQUEST_EVENT_CREATE_SUCCESS = "REQUEST_EVENT_CREATE_SUCCESS";
export const REQUEST_EVENT_CREATE_FAILED = "REQUEST_EVENT_CREATE_FAILED";

export const SELECT_EVENT_NAME = "SELECT_EVENT_NAME";
export const SELECT_EVENT_TYPE = "SELECT_EVENT_TYPE";
export const SELECT_EVENT_DATE = "SELECT_EVENT_DATE";
export const RESTORE_EVENT_CREATE = "RESTORE_EVENT_CREATE";
