export const REQUEST_PLACES_PENDING = 'REQUEST_PLACES_PENDING';
export const REQUEST_PLACES_SUCCESS = 'REQUEST_PLACES_SUCCESS';
export const REQUEST_PLACES_FAILED = 'REQUEST_PLACES_FAILED';

export const REQUEST_EVENT_TYPES_PENDING = 'REQUEST_EVENT_TYPES_PENDING';
export const REQUEST_EVENT_TYPES_SUCCESS = 'REQUEST_EVENT_TYPES_SUCCESS';
export const REQUEST_EVENT_TYPES_FAILED = 'REQUEST_EVENT_TYPES_FAILED';

export const SELECT_EVENT_CITY = 'SELECT_CITY';
export const SELECT_EVENT_TYPE = 'SELECT_EVENT_TYPE';
export const SELECT_EVENT_DATE = 'SELECT_EVENT_DATE';